skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: x64
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
cache: C:\tools\vcpkg\installed\
before_build:
- ps: >-
    $packages = @(
        "boost-filesystem",
        "boost-signals2",
        "boost-interprocess",
        "boost-test",
        "libevent",
        "openssl",
        "zeromq",
        "berkeleydb",
        "secp256k1",
        "leveldb"
    )

    for ($i=0; $i -lt $packages.length; $i++) {
        $all_packages += $packages[$i] + ":" + $env:PLATFORM + "-windows-static "
    }

    Invoke-Expression -Command "vcpkg install $all_packages"
build:
  project: build_msvc\bitcoin.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: build_msvc\%PLATFORM%\Release\test_bitcoin.exe
deploy: off
